---
version: '3'
services:
  w3cstats:
    image: w3cstats:latest
    build: .
    command: /sup/scripts/watch-log -l /tmp/tests/access.log -t 10
    tty: yes
    volumes:
        - ./tests:/tmp/tests
