---
version: '3'
services:
  w3cstats:
    image: w3cstats:latest
    build: .
    command: /sup/scripts/read-file -l /tmp/tests/access.log -s 10
    tty: yes
    volumes:
        - ./tests:/tmp/tests
